### ISSUE TITLE
Default for iconv on Solaris?

### ISSUE THREAD

**Issue by Flamefire** [boostorg/locale#101]
@artyom-beilis What is the intended semantic behind https://github.com/boostorg/locale/blob/f44b3bb771f01fb94614260d57e1d09cdfe1cdff/build/Jamfile.v2#L212-L214 

Should that mean either:
- Never use Iconv on Solaris ? 
- Default to not using Iconv on Solaris ?

**Comment by artyom-beilis** [comment]
There are two variants of iconv on Solaris:

1. One the comes with OS it is buggy
2. There is GNU iconv it is fine

So I try to avoid it.

So the logic is following I use iconv under two conditions

1. User explicitly asked for iconv (maybe because he wants to use GNU iconv)
2. We are not on Solaris - we use it unless the user set iconv explicitly to off.

So ICU uconv API is preferred on Solaris.

**Comment by Flamefire** [comment]
Ok then the condition may be wrong and *always* disable Iconv on Solaris due to undefined operator precedence in B2.
I included parens and a comment to explain this at https://github.com/boostorg/locale/pull/100/commits/58c06603bd6a78fe1a577478fdfee9764c4126df#diff-322788b77c72dedcc9b4a12bf0233ceb8451b4a6baa6d851173ecd5320ac14aeR205-R208

**Comment by artyom-beilis** [comment]
Ohhhh, I see, didn't know that precedence is undefined. 

I hope Boost will switch to CMake finally after 10 years of discussion (wishful thinking)
